#!/usr/bin/env python3
"""
Static pre-flight audit for a Kotlin/Android project that cannot be compiled here.

This is NOT a type checker. It is a targeted search for the specific mistakes you make when
you write Kotlin without a compiler, ranked by how expensive they are at first build:

  1. imports of project symbols that do not exist
  2. R.* references with no matching resource
  3. @Inject sites with no Hilt provider  -> [Dagger/MissingBinding], reported in generated code
  4. .copy(x = ...) naming a property the data class does not have
  5. named arguments at call sites that the target function does not declare
  6. layout ids referenced from code that are absent from the XML

Every finding is printed with file:line so it can be fixed directly. False positives are
possible and are marked; false negatives are certain. Treat it as triage, not proof.
"""
import os, re, sys, json
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KT_DIRS = [os.path.join(ROOT, 'app/src/main/java'),
           os.path.join(ROOT, 'clock-engine/src/main/kotlin')]
RES = os.path.join(ROOT, 'app/src/main/res')

def kt_files():
    for d in KT_DIRS:
        for dp, _, fns in os.walk(d):
            for fn in fns:
                if fn.endswith('.kt'):
                    yield os.path.join(dp, fn)

SRC = {f: open(f, encoding='utf-8').read() for f in kt_files()}

def rel(f): return os.path.relpath(f, ROOT)

def strip_comments(s):
    s = re.sub(r'/\*.*?\*/', '', s, flags=re.S)
    s = re.sub(r'//[^\n]*', '', s)
    return s

NOCOM = {f: strip_comments(s) for f, s in SRC.items()}

def lineno(text, idx): return text.count('\n', 0, idx) + 1

def top_level_named_args(arglist):
    """Named arguments belonging to THIS call only.

    `cancel(firePendingIntent(id, isSnooze = false))` must not report `isSnooze` against
    `cancel` - that was the single biggest source of noise in the first run."""
    out, depth, token, i = [], 0, '', 0
    while i < len(arglist):
        c = arglist[i]
        if c in '([{':
            depth += 1; token = ''
        elif c in ')]}':
            depth -= 1; token = ''
        elif depth == 0:
            if c == ',':
                token = ''
            elif c == '=' and i + 1 < len(arglist) and arglist[i + 1] != '=' and \
                    (i == 0 or arglist[i - 1] not in '=!<>'):
                name = token.strip()
                if re.fullmatch(r'\w+', name):
                    out.append(name)
                token = ''
            else:
                token += c
        i += 1
    return out

findings = defaultdict(list)
def report(cat, f, ln, msg):
    findings[cat].append((rel(f), ln, msg))

# ----------------------------------------------------------------- symbol table
# Top-level declarations per package, plus members of each type.
decl_fqn = set()          # fully qualified top-level names
pkg_of = {}
top_decl_re = re.compile(
    r'^\s*(?:@\w+(?:\([^)]*\))?\s*)*'
    r'(?:public |internal |private |open |abstract |sealed |data |value |annotation |enum |inline |fun )*'
    r'(?:class|interface|object|enum class|fun|val|var|typealias)\s+([A-Za-z_]\w*)', re.M)

top_level_members = set()
ext_re = re.compile(r'^\s*(?:internal |public |private )?'
                    r'(?:fun|val|var)\s+(?:<[^>]+>\s*)?[\w.<>?]+\.(\w+)', re.M)
plain_re = re.compile(r'^(?:internal |public |private )?(?:fun|val|var)\s+(\w+)', re.M)

for f, s in NOCOM.items():
    m = re.search(r'^\s*package\s+([\w.]+)', s, re.M)
    pkg = m.group(1) if m else ''
    pkg_of[f] = pkg
    for mm in top_decl_re.finditer(s):
        decl_fqn.add(pkg + '.' + mm.group(1))
    for mm in ext_re.finditer(s):
        top_level_members.add(pkg + '.' + mm.group(1))
    for mm in plain_re.finditer(s):
        top_level_members.add(pkg + '.' + mm.group(1))

# ----------------------------------------------------------------- 1. imports
for f, s in NOCOM.items():
    for mm in re.finditer(r'^\s*import\s+(com\.digitalclockpro\.[\w.]+)', s, re.M):
        fq = mm.group(1)
        if fq in decl_fqn:
            continue
        # member import: strip the last segment and retry (enum entry, companion member…)
        parent = fq.rsplit('.', 1)[0]
        if parent in decl_fqn:
            continue
        if fq.endswith('.*'):
            continue
        if fq == 'com.digitalclockpro.R' or fq.startswith('com.digitalclockpro.R.'):
            continue  # generated by AAPT at build time, never present in source
        if fq in top_level_members:
            continue  # top-level extension fun / property with a receiver
        report('imports', f, lineno(s, mm.start()), fq)

# ----------------------------------------------------------------- 2. resources
res_names = defaultdict(set)
for dp, _, fns in os.walk(RES):
    kind = os.path.basename(dp).split('-')[0]
    for fn in fns:
        base = fn.rsplit('.', 1)[0]
        if kind in ('drawable', 'layout', 'mipmap', 'raw', 'font', 'xml', 'anim', 'color'):
            res_names[kind].add(base)
        if fn.endswith('.xml') and kind == 'values':
            try:
                txt = open(os.path.join(dp, fn), encoding='utf-8').read()
            except Exception:
                continue
            for tag, attr in [('string', 'string'), ('plurals', 'plurals'), ('color', 'color'),
                              ('dimen', 'dimen'), ('style', 'style'), ('array', 'array'),
                              ('string-array', 'array'), ('integer', 'integer'), ('bool', 'bool')]:
                for nm in re.findall(r'<%s name="([^"]+)"' % tag, txt):
                    res_names[attr].add(nm)
            for nm in re.findall(r'@\+id/([\w_]+)', txt):
                res_names['id'].add(nm)
# ids declared in layouts
for dp, _, fns in os.walk(RES):
    for fn in fns:
        if fn.endswith('.xml'):
            try:
                txt = open(os.path.join(dp, fn), encoding='utf-8').read()
            except Exception:
                continue
            for nm in re.findall(r'@\+id/([\w_]+)', txt):
                res_names['id'].add(nm)

ALIAS = {'mipmap': 'mipmap', 'drawable': 'drawable', 'layout': 'layout', 'raw': 'raw',
         'string': 'string', 'plurals': 'plurals', 'id': 'id', 'color': 'color',
         'dimen': 'dimen', 'style': 'style', 'array': 'array', 'font': 'font',
         'xml': 'xml', 'anim': 'anim', 'integer': 'integer', 'bool': 'bool'}
for f, s in NOCOM.items():
    for mm in re.finditer(r'\bR\.(\w+)\.(\w+)', s):
        kind, name = mm.group(1), mm.group(2)
        if kind not in ALIAS:
            continue
        pool = set(res_names.get(kind, set()))
        if kind == 'drawable':
            pool |= res_names.get('mipmap', set())
        if kind == 'color':
            pool |= res_names.get('color', set())
        if name not in pool:
            report('resources', f, lineno(s, mm.start()), 'R.%s.%s' % (kind, name))

# ----------------------------------------------------------------- 3. Hilt graph
provided = set()
# @Provides / @Binds return types
for f, s in NOCOM.items():
    for mm in re.finditer(r'@(?:Provides|Binds)[\s\S]{0,200}?fun\s+\w+\s*\([^)]*\)\s*:\s*([\w.<>, ?]+)', s):
        t = mm.group(1).strip().split('<')[0].split('.')[-1].rstrip('?')
        provided.add(t)
    # @Binds abstract fun x(impl: Foo): Bar
    for mm in re.finditer(r'@Binds[\s\S]{0,120}?:\s*([\w.]+)', s):
        provided.add(mm.group(1).split('.')[-1])
# @Inject constructors make the type itself bindable
for f, s in NOCOM.items():
    for mm in re.finditer(r'(?:class|object)\s+(\w+)[^\n{]*?@Inject\s+constructor', s):
        provided.add(mm.group(1))
    for mm in re.finditer(r'@(?:Singleton|HiltViewModel|HiltWorker)[\s\S]{0,200}?class\s+(\w+)', s):
        provided.add(mm.group(1))

FRAMEWORK_OK = {
    'Context', 'Application', 'CoroutineScope', 'CoroutineDispatcher', 'SavedStateHandle',
    'WorkerParameters', 'AppWidgetManager', 'Vibrator', 'NotificationManager', 'AlarmManager',
    'Set', 'Map', 'List',
    # Provided by Hilt's own integrations, not by our modules.
    'HiltWorkerFactory', 'WorkerFactory', 'Configuration',
}
inject_fields = []
for f, s in NOCOM.items():
    for mm in re.finditer(r'@Inject\s+(?:lateinit\s+var|val|var)\s+\w+\s*:\s*([\w.]+)', s):
        inject_fields.append((f, lineno(s, mm.start()), mm.group(1).split('.')[-1]))
    for mm in re.finditer(r'@Inject\s+constructor\s*\(([\s\S]*?)\)\s*[:{]', s):
        body = mm.group(1)
        ln = lineno(s, mm.start())
        for p in re.finditer(r':\s*([\w.]+)', body):
            inject_fields.append((f, ln, p.group(1).split('.')[-1]))
for f, ln, t in inject_fields:
    if t in FRAMEWORK_OK or t in provided:
        continue
    report('hilt', f, ln, t)

# ----------------------------------------------------------------- 4. data class fields / .copy()
data_fields = {}
for f, s in NOCOM.items():
    for mm in re.finditer(r'data class\s+(\w+)\s*\(', s):
        name = mm.group(1)
        i = mm.end() - 1
        depth, j = 0, i
        while j < len(s):
            if s[j] == '(': depth += 1
            elif s[j] == ')':
                depth -= 1
                if depth == 0: break
            j += 1
        body = s[i + 1:j]
        fields = set(re.findall(r'(?:^|,)\s*(?:@\w+(?:\([^)]*\))?\s*)*(?:val|var)\s+(\w+)\s*:', body))
        data_fields.setdefault(name, set())
        data_fields[name] |= fields

# receiver-typed copy is hard; only check `X.copy(` and `SomeType(...)` named args below.
# Instead: check every `.copy(` whose named args match NO data class at all.
all_field_names = set().union(*data_fields.values()) if data_fields else set()
for f, s in NOCOM.items():
    for mm in re.finditer(r'\.copy\s*\(([^()]*(?:\([^()]*\)[^()]*)*)\)', s):
        args = top_level_named_args(mm.group(1))
        for a in args:
            if a not in all_field_names:
                report('copy', f, lineno(s, mm.start()), '.copy(%s = ...)' % a)

# ----------------------------------------------------------------- 5. named arguments
func_params = defaultdict(set)
for f, s in NOCOM.items():
    for mm in re.finditer(r'\bfun\s+(?:<[^>]+>\s*)?(?:[\w.]+\.)?(\w+)\s*\(', s):
        name = mm.group(1)
        i = mm.end() - 1
        depth, j = 0, i
        while j < len(s):
            if s[j] == '(': depth += 1
            elif s[j] == ')':
                depth -= 1
                if depth == 0: break
            j += 1
        body = s[i + 1:j]
        for p in re.finditer(r'(?:^|,)\s*(?:@\w+(?:\([^)]*\))?\s*)*(?:vararg\s+|crossinline\s+|noinline\s+)?(\w+)\s*:', body):
            func_params[name].add(p.group(1))
# constructors: class X(val a, b)
for f, s in NOCOM.items():
    for mm in re.finditer(r'\b(?:data\s+|value\s+)?class\s+(\w+)[^\n({]*\(', s):
        name = mm.group(1)
        i = s.index('(', mm.start())
        depth, j = 0, i
        while j < len(s):
            if s[j] == '(': depth += 1
            elif s[j] == ')':
                depth -= 1
                if depth == 0: break
            j += 1
        body = s[i + 1:j]
        for p in re.finditer(r'(?:^|,)\s*(?:@\w+(?:\([^)]*\))?\s*)*(?:val\s+|var\s+)?(\w+)\s*:', body):
            func_params[name].add(p.group(1))

KNOWN_EXTERNAL = set()  # anything we cannot see (androidx, kotlin stdlib) -> skipped
for f, s in NOCOM.items():
    for mm in re.finditer(r'\b([A-Za-z_]\w*)\s*\(([^()]*(?:\([^()]*\)[^()]*){0,6})\)', s):
        callee = mm.group(1)
        if callee not in func_params:
            continue  # not one of ours: cannot check
        if callee in ('if', 'while', 'for', 'when', 'return', 'catch'):
            continue
        args = top_level_named_args(mm.group(2))
        for a in args:
            if a not in func_params[callee]:
                report('namedargs', f, lineno(s, mm.start()),
                       '%s(%s = ...)  declared: %s' %
                       (callee, a, ', '.join(sorted(func_params[callee])[:8])))

# ----------------------------------------------------------------- output
order = [('imports',  'Unresolved project imports'),
         ('resources','Missing R.* resources'),
         ('hilt',     'Possible Hilt MissingBinding'),
         ('copy',     'copy() names an unknown property'),
         ('namedargs','Named argument not declared by the target'),
         ]
total = 0
for key, title in order:
    rows = findings[key]
    seen, uniq = set(), []
    for r in rows:
        if r not in seen:
            seen.add(r); uniq.append(r)
    print('\n=== %s: %d ===' % (title, len(uniq)))
    for fn, ln, msg in sorted(uniq):
        print('  %s:%s  %s' % (fn, ln, msg))
    total += len(uniq)
print('\nTOTAL FINDINGS: %d' % total)
